In [3]:
import pandas as pd
df= pd.read_csv("../Datasets/titanic.csv")
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [5]:
print("columns, rows:", df.shape)

columns, rows: (891, 12)

#### Data Preparation (We don't want many columns so we are droping uncessary columns)

In [6]:
#droping columns
df= df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'])
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [8]:
#filling nan values
df['Age']= df['Age'].fillna(df['Age'].median())

df['Embarked']= df['Embarked'].fillna(df['Embarked'].mode()[0]) #select the first returned mode

In [9]:
#turning text columns into numeric 0/1 columns by One-Hot Encoding
df= pd.get_dummies(df, columns= ["Sex", "Embarked"], drop_first=True)

In [11]:
print('missing values left:', df.isnull().sum().sum())
df.head()

missing values left: 0

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,7.2500,True,False,True
1,1,1,38.0,1,0,71.2833,False,False,False
2,1,3,26.0,0,0,7.9250,False,False,True
3,1,1,35.0,1,0,53.1000,False,False,True
4,0,3,35.0,0,0,8.0500,True,False,True

#### Features, target and train_test_split

In [13]:
from sklearn.model_selection import train_test_split

X= df.drop(columns= "Survived")
y= df["Survived"]

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, stratify=y, random_state=2)

print("train:", X_train.shape[0], "test:", X_test.shape[0])

train: 712 test: 179